import type { Metadata } from "next";
import "../components/ui/globals.css";
import Navbar from "@/components/ui/Navbar";
import { inter } from "@/components/ui/fonts";
import { ThemeProvider } from "@/components/theme-provider";
import Container from "@/components/ui/Container";
import ClientProviders from "@/components/ui/ClientProviders";
import FirebaseAuthProvider from "@/components/FirebaseAuthProvider";

export const metadata: Metadata = {
  title: "Chat with me app",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClientProviders>
      <html lang="en" suppressHydrationWarning>
        <body className={`${inter.className}`}>
          <FirebaseAuthProvider>
            <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
              <Navbar />
              <Container>{children}</Container>
            </ThemeProvider>
          </FirebaseAuthProvider>
        </body>
      </html>
    </ClientProviders>
  );
}
